* LEOPARD analyzer
- Takes in a compile_commands.json file(generated from gen_cc.py), and collects vulnerability and complexity metrics on all functions defined in the compile_commands.json
- The metrics are based on the [[https://arxiv.org/abs/1901.11479][LEOPARD: Identifying Vulnerable Code for Vulnerability Assessment through Program Metrics]] paper
* How to run
** System requirements
- Requires [[https://github.com/rizsotto/Bear][Build EAR]] in order to generate compilation database
- analyzer.py needs a compile_commands.json file which can be generated with gen_cc.py
** For RIOT
A `compile_commands.json` for the selected board can be generated by running inside the application
folder the following:

#+BEGIN_SRC Bash
make compile-commands
#+END_SRC

This target will honor the variables controlling the build process such as `BOARD`, `TOOLCHAIN`,
`DEVELHELP`, etc. just like the usual build process. This works without actual compilation. By
default, the `compile_commands.json` is placed in the RIOT base directory. This behavior can be
overwritten using the `COMPILE_COMMANDS_PATH` variable by specifying the full absolute path
(including file name) of the `compile_commands.json` instead.

***Note:*** By default, the built-in include search directories of GCC will be explicitly added
and flags incompatible with `clangd` will be dropped. This will allow using `clangd` as language
server out of the box. If this is not desired, run `export COMPILE_COMMANDS_FLAGS=""` to turn
modification of the compile commands off. For a list of available flags, run
`./dist/tools/compile_commands/compile_commands.py --help` in the RIOT base directory.
** gen_cc.py:
usage: gen_cc.py [-h] --riotbase RIOTBASE --board BOARD [-j JOBS] [--clean] [--bear BEAR] app_dir

Generate compile_commands.json for a RIOT app directory using bear.

positional arguments:
  app_dir              Path to RIOT app directory

options:
  -h, --help           show this help message and exit
  --riotbase RIOTBASE  Path to RIOT base directory
  --board BOARD        RIOT board (e.g., native)
  -j, --jobs JOBS      Parallel jobs for make
  --clean              Run make clean before building
  --bear BEAR          Path to bear binary (or name on PATH)
** analyzer.py:
usage: analyzer.py [-h] [--target TARGET] [--sysroot SYSROOT] target_dir

Analyze C/C++ functions defined in a CCDB(compile_commands.json) using LEOPARD-style metrics.

positional arguments:
  target_dir         Directory containing the compile_commands.json file

options:
  -h, --help         show this help message and exit
  --target TARGET    Clang target ABI (e.g., arm-none-eabi).
  --sysroot SYSROOT  Sysroot path for the target toolchain.
** Example usage:
#+BEGIN_SRC Bash
python3 gen_cc.py --riotbase ~/Documents/CBMC/analyzer/RIOT/ --board b-l072z-lrwan1 ~/Documents/CBMC/analyzer/RIOT/examples/networking/gnrc/lorawan/
# target_dir for analyzer.py should contain compile_commands.json
python3 analyzer.py ~/Documents/RIOT/examples/networking/gnrc/lorawan/ --sysroot /usr/lib/arm-none-eabi
#+END_SRC
* Output
- Each row represents one function's metrics
- Each column corresponds to a specific complexity of vulnerability metric
* Metrics explanation
** Complexity metrics
*** C1: Cyclomatic complexity
- Number of linearly independent paths through a function
*** Loop structure metrics
- C2: Number of loops
- C3: Number of nested loops
- C4: Maximum nesting level
*** Binning strategy
- Computer complexity score by adding all complexity metric values, group functions with same score into the same bin
** Vulnerability metrics
*** Dependencies
- Dependency relationship of a function with other functions
- V1: Number of parameter variables
- V2: Number of variables prepared by the function as parameters of function calls
*** Pointer metrics
- Captures manipulation of pointers
- # of pointer arithmetic metrics can be obtained from the AST
- V3: # of pointer arithmetic operations
- V4: # of unique variables used in pointer arithmetic
- V5: Max pointer arithmetic a variable is involved in
*** Control structures
- V6: # of nested control structures
- V7: Max nesting level of control structures
- V8: Maximum of control structures that are control-dependent
- V9: Maximum of data-dependent control structures
- V10: # of if statements without explicit else statement
- V11: # of variables involved in control predicates
* Relevant papers:
- [[https://arxiv.org/abs/1901.11479][LEOPARD: Identifying Vulnerable Code for Vulnerability Assessment through Program Metrics]]
- [[https://sites.google.com/site/leopardsite2017/home][LEOPARD detailed metrics]]
