# Defines the root of the project.
# Be aware of how many directories deep you go!

# The value of root changes project by project but for now I'll have it be the static RIOT path
ROOT ?= {ROOT}

# Harness to utilize, omit the extension!
H_ENTRY = {H_ENTRY}

# Extra CBMC flags to be passed during CBMC analysis
H_CBMCFLAGS = --nondet-static --unwind 2 # Rest to be filled in by LLM

# goto-instrument flags to replace function pointers with models
FUNCTION_POINTER_REPL = \

# Env vars, filled in by LLM
H_DEF = {H_DEF}

# LLM should add more to this
H_INC = -I$(ROOT) \
        -I$(ROOT)/sys/include/  \
        -I$(ROOT)/core/lib/include/  \
        -I$(ROOT)/core/include/  \
        -I$(ROOT)/cpu/native/include/  \
        -I$(ROOT)/drivers/include/ \

MAKE_INCLUDE_PATH ?= ..

# Extra function model files to be linked into the harness
LINK = $(MAKE_INCLUDE_PATH)/general-stubs.c

# Include our special build file
include $(MAKE_INCLUDE_PATH)/Makefile.include
